# Generated by Django 4.1.5 on 2023-01-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='experienceInYears',
            field=models.IntegerField(default=0),
        ),
    ]
